apiVersion: v1
kind: Pod
metadata:
  name: mb-pod
#  namespace: dev
  labels:
    app: mb-app
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: mb-config
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
        requests:
          memory: "32Mi"
          cpu: "250m"