apiVersion: v1
kind: Service
metadata:
  name: helloworld-frontend
spec:
  selector:
    app: front-end
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30555