apiVersion: v1
kind: Pod
metadata:
  name: mb-ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: michalbarc/ubuntu-sleeper
#      command: [""] - overrides the entrypoint
      args: ["10"]
      env:
        - name: STRATEGY
          value: default
  restartPolicy: Never