spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: *

zuul:
  prefix: /api/v1
  routes:
    reservation-service:
      path: /reservations/**
      # url: http://localhost:4000
      serviceId: reservation-service
      sensitiveHeaders:
    rating-service:
      path: /ratings/**
      serviceId: rating-service
      sensitiveHeaders: